coverage:
  range: "0...100"
  ignore:          # files and folders that will be removed during processing
    - "etelemetry/_version.py"
    - "setup.py"
    - "versioneer.py"
    - "etelemtry/tests"
